// Atividade pratica - Try, Catch 02

try {
    console.log('Iniciando processamento');
    // a // gera o erro
} catch (error) {
    console.log(`[ERRO] - ${error}`);
} finally {
    console.log('Fim do processo');
}